# Practice Functions

In [1]:
def add(num1 , num2):
    return add

def sub(num1 , num2):
    return sub

def mul(num1 , num2):
    return mul

def div(num1 , num2):
    return div

num1 = int(input("Enter the First Number"))
num2 = int(input("Enter the Second Number"))

print(add(num1,num2))
print(sub(num1,num2))
print(mul(num1,num2))
print(div(num1,num2))

<function add at 0x000001A2E727BB00>
<function sub at 0x000001A2E727BA60>
<function mul at 0x000001A2E727BE20>
<function div at 0x000001A2E73AAFC0>


# Scope of Variables
### Local and Global Variables

In [2]:
def g(y):
    print(x)
    print(x+1)
x=5
g(x)
print(x)

5
6
5


In [3]:
def g(x):
    print(x)
    print(x+1)
name=5
g(name)
print(name)

5
6
5


In [4]:
def f(y):
    x = 1
    x += 1
    print(x)
x=5
f(x)
print(x)

2
5


In [5]:
def f(y):
    y = 1
    y += 1
    print(y)
x=5
f(x)
print(x)

2
5


In [6]:
def f(y):
    y = 2
    y += 1
    print(y)
y=5
f(y)
print(y)

3
5


In [3]:
def h(y):
    x += 1
x = 5
h(x)
print(x)

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [4]:
def h(x):
    x += 1
x = 5
h(x)
print(x)

5


In [5]:
def f(x):
    x = x+1
    print('in f(x):x = ', x)
    return x
x = 3
z = f(x)
print('in main program scope: z =' ,z)
print('in main program scope: x =' ,x)

in f(x):x =  4
in main program scope: z = 4
in main program scope: x = 3


# Nested Function

In [ ]:
def function1():   # Outer Function
    print('Hello from outer function')
    def function2(): # Inner Function
        print('Hello from inner function')
    function2()
function1()

Hello from outer function
Hello from inner function


In [7]:
def num1(x):
    def num2(y):
        return x*y
    return num2

res = num1(10)
print(res)
print(res(5))

<function num1.<locals>.num2 at 0x000001C5479D9260>
50


In [9]:
def num1(x):
    def num2(y):
        return x*y
    return num2

res = num1(int(input('Enter the Value of X:')))
print(res)
print(res(int(input("Enter the value of Y:"))))

<function num1.<locals>.num2 at 0x000001C5479D9300>
32


In [11]:
def num1(x):
    def num2(y):
        return x**y
    return num2

res = num1(7)
print(res)
print(res(2))

<function num1.<locals>.num2 at 0x000001C5479D9300>
49


In [14]:
def num1(x):
    def num2(y):
        return x**y
    return num2

res = num1(int(input('Enter the Value of Base:')))
print(res)
print(res(int(input("Enter the value of Power:"))))

<function num1.<locals>.num2 at 0x000001C5479D9DA0>
25


In [ ]:
def num1(base):
    def num2(power):
        return base**power
    return num2

res = num1(int(input('Enter the Value of Base:')))
print(res)
print(res(int(input("Enter the value of Power:"))))

In [ ]:
def num1(x):
    def num2(y):
        def num3(z):
            return x*y*z
        return num3
    return num2
res = num1(int(input('Enter the Value of X:')))
print(res)
print(res(int(input("Enter the value of Y:"))))
print(res(int(input("Enter the value of Z:"))))

<function num1 at 0x000001C547A2C9A0>
<function num1 at 0x000001C547A2C9A0>
<function num1 at 0x000001C547A2C9A0>


In [18]:
def num1(x):
    def num2(y):
        def num3(z):
            return x * y * z
        return num3
    return num2

# Step-by-step process
x = int(input('Enter the Value of X: '))
res1 = num1(x)  # num1 returns num2

y = int(input('Enter the Value of Y: '))
res2 = res1(y)  # num2 returns num3

z = int(input('Enter the Value of Z: '))
result = res2(z)  # num3 returns the final result

print("The result of x * y * z is:", result)


The result of x * y * z is: 27


Syed Muhammad Ovais ye result mai ana chahiye aik 7 
isi nested function sy input ly k

In [23]:
def name1(x):
  def name2(y):
    def name3(z):
      return x+y+z
    return name3
  return name2  

res = name1('M ')
print(res)
res1 = res('Nihal')
print(res1(" Iqbal"))

<function name1.<locals>.name2 at 0x000001C547A2CEA0>
M Nihal Iqbal


# Libraries

In [1]:
import pandas as pd
import numpy as np


In [7]:
data = np.arange(24).reshape(4,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
import pandas as pd
import numpy as np

data = np.arange(30).reshape(5,6)

In [12]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [8]:
data1=np.arange(30,60).reshape(5,6)
data1

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [13]:
type(data1)

numpy.ndarray

In [16]:
data2 = np.linspace(20,10,1)
data2

array([20.])

In [17]:
data2 = np.linspace(20,10,2)
data2

array([20., 10.])

In [18]:
data2 = np.linspace(20,10,3)
data2

array([20., 15., 10.])

In [19]:
data2 = np.linspace(20,10,4)
data2

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [20]:
data2 = np.linspace(20,10,10)
data2

array([20.        , 18.88888889, 17.77777778, 16.66666667, 15.55555556,
       14.44444444, 13.33333333, 12.22222222, 11.11111111, 10.        ])

In [26]:
np.random.randint(10)

3

# PANDAS

In [28]:
# Dataframe is a composition of indices
df = pd.DataFrame(data1)
df

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [48]:
data1,index = ['Row1','Row2','Row3','Row4','Row5'],['Column1','Column2','Colum3','Columns4','Columns5']

In [49]:
df.replace(data1,index)

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [33]:
df.columns

RangeIndex(start=0, stop=6, step=1)

In [34]:
df.shape

(5, 6)

In [35]:
df.head()

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [36]:
df.sample()

0   1   2   3   4   5
4  54  55  56  57  58  59

In [37]:
df.describe()

0          1          2          3          4          5
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
 1   1       5 non-null      int64
 2   2       5 non-null      int64
 3   3       5 non-null      int64
 4   4       5 non-null      int64
 5   5       5 non-null      int64
dtypes: int64(6)
memory usage: 372.0 bytes


In [54]:
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [55]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Game', 'Productivity', 'Productivity', 'Productivity', 'Game',
        'Game', 'Productivity', 'Productivity', 'Game', 'Productivity',
        'Productivity', 'Productivity', 'Education', 'Education', 'Game',
        'Education', 'Education', 'Game', 'Health', 'Health', 'Education',
        'Productivity', 'Game', 'Education', 'Productivity', 'Education',
        'Education', 'Health', 'Productivity', 'Productivity'],
       dtype='<U12'),
 'Rating': array([3.4, 4.2, 2. , 3.6, 4.8, 3.3, 2.9, 1.5, 1.9, 2.5, 2.1, 2.2, 4.3,
        4. , 4.1, 3.9, 4.6, 4.1, 1.8, 4.4, 1.9, 4.3, 2.8, 2. , 3.6, 3.5,
        3.8, 3.5, 4.

In [56]:
df = pd.DataFrame(data)
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1          Game     3.4     6537                 10M   50,000+  Paid   
1    App_2  Productivity     4.2     3641  Varies with device   50,000+  Paid   
2    App_3  Productivity     2.0     5175                 20M   10,000+  Paid   
3    App_4  Productivity     3.6     6715                 30M    1,000+  Paid   
4    App_5          Game     4.8     9801                 20M   10,000+  Free   
5    App_6          Game     3.3     7833  Varies with device   50,000+  Free   
6    App_7  Productivity     2.9     7968  Varies with device    1,000+  Paid   
7    App_8  Productivity     1.5     8162  Varies with device   10,000+  Paid   
8    App_9          Game     1.9     3138                 10M  100,000+  Paid   
9   App_10  Productivity     2.5     4065                 30M    1,000+  Paid   
10  App_11  Productivity     2.1     3877  Varies with device    1,000+  Free   
11  App_12  Productivity     2.2      487                 30M  100,000+  Free   
12  App_13     Education     4.3     3439  Varies with device   50,000+  Free   
13  App_14     Education     4.0     6616  Varies with device    1,000+  Free   
14  App_15          Game     4.1     5398  Varies with device   50,000+  Free   
15  App_16     Education     3.9     7201                 30M   10,000+  Free   
16  App_17     Education     4.6     6258                 10M   50,000+  Free   
17  App_18          Game     4.1     8342                 30M   50,000+  Paid   
18  App_19        Health     1.8     6347                 20M    1,000+  Free   
19  App_20        Health     4.4     1702                 30M  100,000+  Paid   
20  App_21     Education     1.9     8475                 20M   50,000+  Free   
21  App_22  Productivity     4.3     7798  Varies with device  100,000+  Paid   
22  App_23          Game     2.8     6592  Varies with device   50,000+  Free   
23  App_24     Education     2.0     8733                 10M    1,000+  Paid   
24  App_25  Productivity     3.6     7469  Varies with device   10,000+  Free   
25  App_26     Education     3.5     6391                 10M  100,000+  Paid   
26  App_27     Education     3.8     6209                 20M    1,000+  Free   
27  App_28        Health     3.5     2414                 30M   50,000+  Paid   
28  App_29  Productivity     4.5     4556                 10M   50,000+  Paid   
29  App_30  Productivity     1.4     5306                 30M   50,000+  Paid   

   Price Content Rating  
0   9.99   Everyone 10+  
1   9.99   Everyone 10+  
2   4.99           Teen  
3      0       Everyone  
4   1.99   Everyone 10+  
5   5.99     Mature 17+  
6   5.99   Everyone 10+  
7   5.99     Mature 17+  
8      0   Everyone 10+  
9   1.99           Teen  
10  0.99     Mature 17+  
11     0           Teen  
12     0           Teen  
13  4.99           Teen  
14  2.99           Teen  
15  9.99       Everyone  
16  2.99       Everyone  
17  5.99   Everyone 10+  
18  5.99     Mature 17+  
19     0           Teen  
20  9.99       Everyone  
21  5.99       Everyone  
22  0.99       Everyone  
23  4.99           Teen  
24  9.99       Everyone  
25  1.99           Teen  
26  4.99     Mature 17+  
27  0.99       Everyone  
28  5.99   Everyone 10+  
29  2.99     Mature 17+

In [58]:
type(df.App)

pandas.core.series.Series

In [59]:
df.head()

App      Category  Rating  Reviews                Size Installs  Type  \
0  App_1          Game     3.4     6537                 10M  50,000+  Paid   
1  App_2  Productivity     4.2     3641  Varies with device  50,000+  Paid   
2  App_3  Productivity     2.0     5175                 20M  10,000+  Paid   
3  App_4  Productivity     3.6     6715                 30M   1,000+  Paid   
4  App_5          Game     4.8     9801                 20M  10,000+  Free   

  Price Content Rating  
0  9.99   Everyone 10+  
1  9.99   Everyone 10+  
2  4.99           Teen  
3     0       Everyone  
4  1.99   Everyone 10+

In [60]:
df.tail()

App      Category  Rating  Reviews Size  Installs  Type Price  \
25  App_26     Education     3.5     6391  10M  100,000+  Paid  1.99   
26  App_27     Education     3.8     6209  20M    1,000+  Free  4.99   
27  App_28        Health     3.5     2414  30M   50,000+  Paid  0.99   
28  App_29  Productivity     4.5     4556  10M   50,000+  Paid  5.99   
29  App_30  Productivity     1.4     5306  30M   50,000+  Paid  2.99   

   Content Rating  
25           Teen  
26     Mature 17+  
27       Everyone  
28   Everyone 10+  
29     Mature 17+

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [64]:
df.sample()

App      Category  Rating  Reviews Size Installs  Type Price  \
3  App_4  Productivity     3.6     6715  30M   1,000+  Paid     0   

  Content Rating  
3       Everyone

In [67]:
df.Price

0     9.99
1     9.99
2     4.99
3        0
4     1.99
5     5.99
6     5.99
7     5.99
8        0
9     1.99
10    0.99
11       0
12       0
13    4.99
14    2.99
15    9.99
16    2.99
17    5.99
18    5.99
19       0
20    9.99
21    5.99
22    0.99
23    4.99
24    9.99
25    1.99
26    4.99
27    0.99
28    5.99
29    2.99
Name: Price, dtype: object

In [69]:
df[['App','Price','Size']]

App Price                Size
0    App_1  9.99                 10M
1    App_2  9.99  Varies with device
2    App_3  4.99                 20M
3    App_4     0                 30M
4    App_5  1.99                 20M
5    App_6  5.99  Varies with device
6    App_7  5.99  Varies with device
7    App_8  5.99  Varies with device
8    App_9     0                 10M
9   App_10  1.99                 30M
10  App_11  0.99  Varies with device
11  App_12     0                 30M
12  App_13     0  Varies with device
13  App_14  4.99  Varies with device
14  App_15  2.99  Varies with device
15  App_16  9.99                 30M
16  App_17  2.99                 10M
17  App_18  5.99                 30M
18  App_19  5.99                 20M
19  App_20     0                 30M
20  App_21  9.99                 20M
21  App_22  5.99  Varies with device
22  App_23  0.99  Varies with device
23  App_24  4.99                 10M
24  App_25  9.99  Varies with device
25  App_26  1.99                 10M
26  App_27  4.99                 20M
27  App_28  0.99                 30M
28  App_29  5.99                 10M
29  App_30  2.99                 30M

In [70]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.230000  5888.166667
std     1.050501  2256.842623
min     1.400000   487.000000
25%     2.125000  4187.750000
50%     3.500000  6369.000000
75%     4.100000  7715.750000
max     4.800000  9801.000000

In [72]:
df.shape

(30, 9)

In [74]:
df['Size'].unique()

array(['10M', 'Varies with device', '20M', '30M'], dtype=object)

In [76]:
df['Reviews'].unique()

array([6537, 3641, 5175, 6715, 9801, 7833, 7968, 8162, 3138, 4065, 3877,
        487, 3439, 6616, 5398, 7201, 6258, 8342, 6347, 1702, 8475, 7798,
       6592, 8733, 7469, 6391, 6209, 2414, 4556, 5306], dtype=int32)

In [77]:
df['Installs'].unique()

array(['50,000+', '10,000+', '1,000+', '100,000+'], dtype=object)

In [78]:
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [79]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [80]:
df['Price'].unique()

array(['9.99', '4.99', '0', '1.99', '5.99', '0.99', '2.99'], dtype=object)

In [81]:
df['Price'].replace('Free','0')

0     9.99
1     9.99
2     4.99
3        0
4     1.99
5     5.99
6     5.99
7     5.99
8        0
9     1.99
10    0.99
11       0
12       0
13    4.99
14    2.99
15    9.99
16    2.99
17    5.99
18    5.99
19       0
20    9.99
21    5.99
22    0.99
23    4.99
24    9.99
25    1.99
26    4.99
27    0.99
28    5.99
29    2.99
Name: Price, dtype: object

In [83]:
df['Price'] = df['Price'].replace('Free','0')